# Generated by Django 4.2.23 on 2025-08-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_time', models.IntegerField(default=0, help_text='Ümumi hazırlanma vaxtı (dəqiqə)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_num', models.IntegerField(help_text='Masanın nömrəsi', unique=True)),
                ('status', models.CharField(choices=[('empty', 'Boş'), ('reserved', 'Rezerv'), ('occupied', 'Dolu')], default='empty', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('description_az', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vegan', models.BooleanField(default=False)),
                ('halal', models.BooleanField(default=False)),
                ('time', models.IntegerField(help_text='Hazırlanma vaxtı (dəqiqə)')),
                ('image', models.ImageField(upload_to='products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pmsfoodmenu.category')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('name_az', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('description_az', models.TextField()),
                ('description_en', models.TextField()),
                ('description_ru', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time', models.IntegerField(help_text='Hazırlanma vaxtı (dəqiqə)')),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pmsfoodmenu.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmsfoodmenu.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='pmsfoodmenu.table'),
        ),
    ]
