# Generated by Django 4.2.23 on 2025-08-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsfoodmenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('empty', 'Boş'), ('reserved', 'Rezerv'), ('ordered', 'Sifariş'), ('waitingFood', 'Yemək gözləyir'), ('waitingWaite', 'Ofisiant gözləyir')], default='empty', max_length=20),
        ),
    ]
